# Generated by Django 5.0.1 on 2024-02-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_videocomment_uploadedvideo_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='comments',
        ),
    ]
