# Generated by Django 5.0.1 on 2024-02-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_rename_author_videocomment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoComment',
        ),
    ]
